server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/wall
    username: ivan
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  main:
    web-application-type: servlet